refactor/fix: split into components, fix imports and fix item loading bug after login
NationalLibraryOfNorway/ammo pull request #12
Opened 2024-11-13 12:40 UTC by fredrikmonsen

2024-12-02 12:22 UTC, Sindrir requested changes

2024-12-02 12:22 UTC, Sindrir commented on src/components/ui/Header.tsx
> +          ) : <></>}
Burde vel foretrekke `&&` for conditional rendering hvis ingenting skal rendres for `false`

2024-12-02 12:22 UTC, Sindrir commented on src/features/metadata-form.tsx
> +  }, [props.extractedMetadata.title, props.extractedMetadata.titleId, setValue]);
Hvorfor pakkes `setValue` funksjonen som en dependency her? Den er vel ikke en verdi under endring

2024-12-02 12:37 UTC, fredrikmonsen commented on src/features/metadata-form.tsx
> +  }, [props.extractedMetadata.title, props.extractedMetadata.titleId, setValue]);
eslint klager dersom man ikke har den med, blir vel sånn når den er hentet fra react-hook-form :man_shrugging:

2024-12-02 12:38 UTC, fredrikmonsen commented on src/components/ui/Header.tsx
> +          ) : <></>}
Fikset

2024-12-13 14:12 UTC, Sindrir approved these changes

2024-12-13 14:13 UTC, merged